### ISSUE TITLE
支持哪些编码

### ISSUE THREAD

**Issue by SkyCJC** [ILoveLin/VlcRecordPlayer#15]
录像时，换成rtmp格式的视频流，提示录像成功，去查看文件时显示文件大小为0

**Comment by ILoveLin** [comment]
都支持的，你尝试看下 你权限是否申请成功~

**Comment by SkyCJC** [comment]
> 都支持的，你尝试看下 你权限是否申请成功~

截图是没问题的，文件、音频权限是打开的

**Comment by SkyCJC** [comment]
> > 都支持的，你尝试看下 你权限是否申请成功~
> 
> 截图是没问题的，文件、音频权限是打开的

-i http://220.161.87.62:8800/hls/0/index.m3u8 -c copy
我这边是直接把中间视频流地址换成rtmp了，这样处理可以的吧

**Comment by ILoveLin** [comment]
你的意思一开始是，http，播着播着，把直播流替换成rtmp？？

**Comment by SkyCJC** [comment]
> 你的意思一开始是，http，播着播着，把直播流替换成rtmp？？

不是，-i rtmp://my-video-address -c copy
这样处理的

**Comment by ILoveLin** [comment]
你用的是里面哪个Demo，vlc 还是ffmpeg-kit？

**Comment by SkyCJC** [comment]
> 你用的是里面哪个Demo，vlc 还是ffmpeg-kit？

是在FFmpegActivity中处理的

**Comment by SkyCJC** [comment]
> > 你用的是里面哪个Demo，vlc 还是ffmpeg-kit？
> 
> 是在FFmpegActivity中处理的

vlc的不能播放rtmp 265编码的

**Comment by ILoveLin** [comment]
ffmpeg 理论上可以录制的，但是你要在切换的时候，主动调用一次，

**Comment by SkyCJC** [comment]
> ffmpeg 理论上可以录制的，但是你要在切换的时候，主动调用一次，

我是直接修改成rtmp跑到手机上的，不是手动改成rtmp的，需要主动调用哪块逻辑
