### ISSUE TITLE
播放rtmp视频流，有画面没有声音

### ISSUE THREAD

**Issue by SkyCJC** [ILoveLin/VlcRecordPlayer#16]
播放rtmp视频流，有画面没有声音，ijkplayer还不能设置probesize，这个怎么修改
录像时，FFmpeg-kit对265编码的视频流不能录像，怎么调整

**Comment by SkyCJC** [comment]
> 这么貌似不能修改

声音没有也不能修改是么

**Comment by ILoveLin** [comment]
你说的没有声音是哪一个Demo

**Comment by SkyCJC** [comment]
FFmpeg demo

**Comment by ILoveLin** [comment]
首先你要确定，你播放的是音视频流，还是纯视频流，自然没有声音，如果你拉去的直播流，是有声音的（可以使用win版本的vlc播放 确认了有声音），大概率是你设置有问题
你去https://github.com/arthenica/ffmpeg-kit  提交个issue 或者issue 记录里面搜下相关问题。就有答案了

**Comment by SkyCJC** [comment]
> 首先你要确定，你播放的是音视频流，还是纯视频流，自然没有声音，如果你拉去的直播流，是有声音的（可以使用win版本的vlc播放 确认了有声音），大概率是你设置有问题 你去https://github.com/arthenica/ffmpeg-kit 提交个issue 或者issue 记录里面搜下相关问题。就有答案了

拉的直播流，有声音的，默认是没有任何设置的，只是配置直播流地址播放，rtmp协议没有声音，hls协议是有声音的，我看FFmpeg的demo中只有录像会使用到FFmpeg-kit，播放相关没有配置的

**Comment by ILoveLin** [comment]
> > 首先你要确定，你播放的是音视频流，还是纯视频流，自然没有声音，如果你拉去的直播流，是有声音的（可以使用win版本的vlc播放 确认了有声音），大概率是你设置有问题 你去https://github.com/arthenica/ffmpeg-kit 提交个issue 或者issue 记录里面搜下相关问题。就有答案了
> 
> 拉的直播流，有声音的，默认是没有任何设置的，只是配置直播流地址播放，rtmp协议没有声音，hls协议是有声音的，我看FFmpeg的demo中只有录像会使用到FFmpeg-kit，播放相关没有配置的

你开启了播放器的 声音设置吗？？

**Comment by SkyCJC** [comment]
> > > 首先你要确定，你播放的是音视频流，还是纯视频流，自然没有声音，如果你拉去的直播流，是有声音的（可以使用win版本的vlc播放 确认了有声音），大概率是你设置有问题 你去https://github.com/arthenica/ffmpeg-kit 提交个issue 或者issue 记录里面搜下相关问题。就有答案了
> > 
> > 
> > 拉的直播流，有声音的，默认是没有任何设置的，只是配置直播流地址播放，rtmp协议没有声音，hls协议是有声音的，我看FFmpeg的demo中只有录像会使用到FFmpeg-kit，播放相关没有配置的
> 
> 你开启了播放器的 声音设置吗？？

配置地址，开启播放前，设置了声音setVolume(1, 1)

**Comment by ILoveLin** [comment]
播放器使用的DK播放器~~~你可以看到的，去问问

**Comment by SkyCJC** [comment]
> 播放器使用的DK播放器~~~你可以看到的，去问问

问了，没回复

**Comment by ILoveLin** [comment]
你现在去下载个win的vlc，你把直播流复制上去，你说的rtmp和hls两种都测试下，看都有声音不，如果测试结果还是和你现在的一样，那就没办法了，如果vlc能用，你就切换成vlc播放器~

**Comment by SkyCJC** [comment]
好的，vlc的延时比较严重，而且265编码的不支持
