### ISSUE TITLE
播放部分IPTV的直播源链接失败

### ISSUE THREAD

**Issue by ForgottenDevil** [ILoveLin/VlcRecordPlayer#2]
如： http://tvmvip110.club/as.php?id=cctv1hd，不确定是库的问题还是其他问题，看log好像是到了文件尾，但Windows端的VLC播放器可以正常播放

**Comment by ILoveLin** [comment]
ndk版本 r13b

**Comment by ILoveLin** [comment]
尝试下 下载android端VLC播放下能播放不?如果官方的vlc(android客户端)不行就不行哦
VLC官方下载地址:https://www.videolan.org/vlc/
