### ISSUE TITLE
您好，请问录屏的文件可以保存为其他格式吗

### ISSUE THREAD

**Issue by xyboo** [ILoveLin/VlcRecordPlayer#4]
首先非常感谢您特意写一个视频直播的项目，并将其开源。
我在使用过程，发现目前录制出的视频只有avi格式的，尝试了多个手机播放器，大部分的播放器打不开，所以想问下后期可以支持mp4等普通的格式吗，谢谢！

**Comment by ILoveLin** [comment]
我记得 我这边录制出来的是.mp4格式的
![0 0 0 0 0 0](https://user-images.githubusercontent.com/20768182/221805554-63916925-92c1-49bb-982e-f4497284d0f4.jpg)

**Comment by xyboo** [comment]
那我晚上再试一下，这个格式会不会和机型或者视频流有关呢

**Comment by ILoveLin** [comment]
> 那我晚上再试一下，这个格式会不会和机型或者视频流有关呢

和机型无关,你可以尝试录制不同的直播流看看结果
试试这个湖南卫视直播地址
http://219.151.31.38/liveplay-kk.rtxapp.com/live/program/live/hnwshd/4000000/mnf.m3u8

**Comment by xyboo** [comment]
> > 那我晚上再试一下，这个格式会不会和机型或者视频流有关呢
> 
> 和机型无关,你可以尝试录制不同的直播流看看结果 试试这个湖南卫视直播地址 http://219.151.31.38/liveplay-kk.rtxapp.com/live/program/live/hnwshd/4000000/mnf.m3u8

我试了一下，这个地址录出来的就是mp4格式的，看来是和视频流有关啊
